on:
  push:

name: Terraform

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v1

    - id: init
      run: terraform init

    - id: plan
      run: terraform plan -no-color

    - id: apply
      run: terraform apply -auto-approve

    - id: output
      run: terraform output

    - run: |
        echo "::add-mask::${{ steps.output.outputs.stdout }}"

    - run: echo "${{ steps.output.outputs.stdout }}"